In [0]:
# importações
import pandas as pd
import pickle
import numpy as np

In [0]:
# Importando os modelos criados
classSVM = pickle.load(open('modelo_svm.sav', 'rb'))
classRandomForest = pickle.load(open('modelo_random_forest.sav', 'rb'))
classLinearRegression = pickle.load(open('modelo_regressao_linear.sav', 'rb'))

In [25]:
# Criando novo dado para testar os modelos
novo_dado = [[	4.9,	3.0,	1.4,	0.2 ]]

# passando o modelo para a forma certa
novo_dado = np.asarray(novo_dado)
print(novo_dado)

[[4.9 3.  1.4 0.2]]


In [26]:
# classificando o novo dado com o svm
classSVM.predict(novo_dado)

array([0])

In [27]:
# Classificando o novo dado com o random forest
classRandomForest.predict(novo_dado)

array([0])

In [28]:
# Classificando o novo dado com a regressão linear
classLinearRegression.predict(novo_dado)

array([[-0.03858976]])